const  ActionTypes = {
    ADD_PRODUCTS : "ADD_PRODUCTS",
    INCREMENT_QUANTITY : "INCREMENT_QUANTITY",
    DECREMENT_QUANTITY : "DECREMENT_QUANTITY",
    LOGIN : "LOGIN",
    LOGOUT: "LOGOUT",
    
}
export default ActionTypes;